name: ${{ format('{0} AI 뉴스 요약', steps.date.outputs.date) }}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 매일 자정(UTC), 한국 시간 오전 9시

permissions:
  contents: write

jobs:
  make-file:
    runs-on: ubuntu-latest
    steps:
      - name: 날짜 설정
        id: date
        run: echo "date=$(TZ='Asia/Seoul' date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: 저장소에 있는 파일 불러오기
        uses: actions/checkout@v4

      - name: Java 17 세팅
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 컴파일 및 코드 실행
        run: |
          javac src/App.java
          java -cp src App
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}

      - name: 실행 결과로 나온 파일을 커밋
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "${{ steps.date.outputs.date }} AI 뉴스 요약"
          add: "."